near_registry_account:
  account_id: hot-validation-test.near
  private_key: ed25519:3672N7DNEtFwKUHVJrv4t5pTxzFnJwuXaCJeJn4TCpdnv7YJjo1kfZviqp6awb9K4wwEzAAXhYcWjWZCRWy1Ru1X
mpc_auth_key: hot-validation-test-auth-key
uid_registry:
  bridge_deposit: a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1
  bridge_withdraw: b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2
