[tasks.test]
env_files = ["tests-data/env"]
env = { "RUST_LOG"="DEBUG" }
command = "cargo"
args = [
    "run",
    "--",
    "--config",
    "tests-data/config.yaml",
    "--output",
    "tests-data/rpc_config.yaml"
]
