name: RPC Fetch build & push

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Image tag (e.g., latest, v1.2.3)"
        required: true
        default: "latest"
        type: string
      platforms:
        description: "Comma-separated platforms"
        required: false
        default: "linux/amd64"
        type: string

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

jobs:
  docker:
    runs-on: ["self-hosted", "repo:hot-validation-sdk"]
    env:
      DOCKER_HOST: tcp://dind:2375
      DOCKER_BUILDKIT: "1"
      IMAGE: ghcr.io/${{ github.repository }}/rpc-fetch
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push (cached, multi-arch)
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: rpc-fetch/Dockerfile
          push: true
          platforms: ${{ github.event.inputs.platforms }}
          tags: |
            ${{ env.IMAGE }}:${{ github.event.inputs.tag }}
            ${{ env.IMAGE }}:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
